apiVersion: v2
name: carku
description: A Helm chart for Carku GPS Server
type: application
version: 1.9.9
appVersion: "5.10"
dependencies:
  - name: mysql
    version: 14.0.3
    repository: https://charts.bitnami.com/bitnami
    condition: mysql.enabled
  - name: postgresql
    version: 18.7.2
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: redis-ha
    version: 4.35.10
    repository: https://dandydeveloper.github.io/charts
    condition: redis-ha.enabled
maintainers:
  - email: borhan.d@gmail.com
    name: Borhan
