{{- if .Values.nominatim.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "carku.fullname" . }}-nominatim-config
  labels:
    {{- include "carku.labels" . | nindent 4 }}
    app: nominatim
data:
  PBF_URL: {{ .Values.nominatim.config.pbfUrl | quote }}
  DATA_LABEL: {{ .Values.nominatim.config.dataLabel | quote }}
  AWS_REGION: {{ .Values.nominatim.config.awsRegion | quote }}
  S3_BUCKET: {{ .Values.nominatim.config.s3Bucket | quote }}
{{- end }}
