{{- if .Values.nominatim.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "carku.fullname" . }}-nominatim-storage-secret
  labels:
    {{- include "carku.labels" . | nindent 4 }}
    app: nominatim
type: Opaque
stringData:
  access-key-id: {{ .Values.nominatim.s3.accessKeyId | quote }}
  secret-access-key: {{ .Values.nominatim.s3.secretAccessKey | quote }}
{{- end }}
