{{- if not .Values.configOverride }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "carku.fullname" . }}
  labels:
    {{- include "carku.labels" . | nindent 4 }}
stringData:
  {{- if .Values.mysql.enabled }}
  DATABASE_USER: {{ .Values.mysql.auth.username | quote }}
  DATABASE_PASSWORD: {{ .Values.mysql.auth.password | quote }}
  {{- else }}
  {{- if ((.Values.carku).database).user }}
  DATABASE_USER: {{ .Values.carku.database.user | quote }}
  {{- end }}
  {{- if ((.Values.carku).database).password }}
  DATABASE_PASSWORD: {{ .Values.carku.database.password | quote }}
  {{- end }}
  {{- end }} {{/* end if mysql.enabled */}}
  {{- if (((.Values.carku).mail).smtp).username }}
  MAIL_SMTP_USERNAME: {{ .Values.carku.mail.smtp.username | quote }}
  {{- end }}
  {{- if (((.Values.carku).mail).smtp).password }}
  MAIL_SMTP_PASSWORD: {{ .Values.carku.mail.smtp.password | quote }}
  {{- end }}
{{- end }}
