{{- if gt (int .Values.replicaCount) 1 }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "carku.fullname" . }}
  labels:
    {{- include "carku.labels" . | nindent 4 }}
spec:
  minAvailable: {{ sub (int .Values.replicaCount) 1 }}
  selector:
    matchLabels:
      {{- include "carku.selectorLabels" . | nindent 6 }}
{{- end }}