{{- if not .Values.configOverride }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "carku.fullname" . }}
  labels:
    {{- include "carku.labels" . | nindent 4 }}
stringData:
  {{- if .Values.mysql.enabled }}
  DATABASE_USER: {{ .Values.mysql.auth.username | quote }}
  DATABASE_PASSWORD: {{ .Values.mysql.auth.password | quote }}
  {{- else if .Values.postgresql.enabled }}
  DATABASE_USER: {{ .Values.postgresql.auth.username | quote }}
  DATABASE_PASSWORD: {{ .Values.postgresql.auth.password | quote }}
  {{- else }}
  {{- if ((.Values.carku).database).user }}
  DATABASE_USER: {{ .Values.carku.database.user | quote }}
  {{- end }}
  {{- if ((.Values.carku).database).password }}
  DATABASE_PASSWORD: {{ .Values.carku.database.password | quote }}
  {{- end }}
  {{- end }}

  {{- if ((.Values.carku).devicePassword) }}
  DEVICE_PASSWORD: {{ .Values.carku.devicePassword | quote }}
  {{- end }}

  {{- if ((.Values.carku).sms).http }}
  {{- if ((.Values.carku).sms.http).authorization }}
  SMS_HTTP_AUTHORIZATION: {{ .Values.carku.sms.http.authorization | quote }}
  {{- end }}
  {{- if ((.Values.carku).sms.http).user }}
  SMS_HTTP_USER: {{ .Values.carku.sms.http.user | quote }}
  {{- end }}
  {{- if ((.Values.carku).sms.http).password }}
  SMS_HTTP_PASSWORD: {{ .Values.carku.sms.http.password | quote }}
  {{- end }}
  {{- end }}

  {{- if ((.Values.carku).sms).aws }}
  {{- if ((.Values.carku).sms.aws).access }}
  SMS_AWS_ACCESS: {{ .Values.carku.sms.aws.access | quote }}
  {{- end }}
  {{- if ((.Values.carku).sms.aws).secret }}
  SMS_AWS_SECRET: {{ .Values.carku.sms.aws.secret | quote }}
  {{- end }}
  {{- if ((.Values.carku).sms.aws).region }}
  SMS_AWS_REGION: {{ .Values.carku.sms.aws.region | quote }}
  {{- end }}
  {{- end }}

  {{- if ((.Values.carku).command).client }}
  {{- if ((.Values.carku).command.client).serviceAccount }}
  COMMAND_CLIENT_SERVICE_ACCOUNT: |-
    {{- .Values.carku.command.client.serviceAccount | nindent 4 }}
  {{- end }}
  {{- end }}

  {{- if ((.Values.carku).command).findHub }}
  {{- if ((.Values.carku).command.findHub).key }}
  COMMAND_FIND_HUB_KEY: {{ .Values.carku.command.findHub.key | quote }}
  {{- end }}
  {{- end }}

  {{- if ((.Values.carku).notificator).carku }}
  {{- if ((.Values.carku).notificator.carku).key }}
  NOTIFICATOR_CARKU_KEY: {{ .Values.carku.notificator.carku.key | quote }}
  {{- end }}
  {{- end }}

  {{- if ((.Values.carku).notificator).firebase }}
  {{- if ((.Values.carku).notificator.firebase).serviceAccount }}
  NOTIFICATOR_FIREBASE_SERVICE_ACCOUNT: |-
    {{- .Values.carku.notificator.firebase.serviceAccount | nindent 4 }}
  {{- end }}
  {{- end }}

  {{- if ((.Values.carku).notificator).pushover }}
  {{- if ((.Values.carku).notificator.pushover).token }}
  NOTIFICATOR_PUSHOVER_TOKEN: {{ .Values.carku.notificator.pushover.token | quote }}
  {{- end }}
  {{- end }}

  {{- if ((.Values.carku).notificator).telegram }}
  {{- if ((.Values.carku).notificator.telegram).key }}
  NOTIFICATOR_TELEGRAM_KEY: {{ .Values.carku.notificator.telegram.key | quote }}
  {{- end }}
  {{- end }}

  {{- if ((.Values.carku).notificator).whatsapp }}
  {{- if ((.Values.carku).notificator.whatsapp).token }}
  NOTIFICATOR_WHATSAPP_TOKEN: {{ .Values.carku.notificator.whatsapp.token | quote }}
  {{- end }}
  {{- end }}

  {{- if ((.Values.carku).orbcomm) }}
  {{- if ((.Values.carku).orbcomm).accessId }}
  ORBCOMM_ACCESS_ID: {{ .Values.carku.orbcomm.accessId | quote }}
  {{- end }}
  {{- if ((.Values.carku).orbcomm).password }}
  ORBCOMM_PASSWORD: {{ .Values.carku.orbcomm.password | quote }}
  {{- end }}
  {{- end }}

  {{- if ((.Values.carku).smartcar) }}
  {{- if ((.Values.carku).smartcar).managementToken }}
  SMARTCAR_MANAGEMENT_TOKEN: {{ .Values.carku.smartcar.managementToken | quote }}
  {{- end }}
  {{- end }}

  {{- if ((.Values.carku).web).serviceAccountToken }}
  WEB_SERVICE_ACCOUNT_TOKEN: {{ .Values.carku.web.serviceAccountToken | quote }}
  {{- end }}

  {{- if ((.Values.carku).openid) }}
  {{- if ((.Values.carku).openid).clientSecret }}
  OPENID_CLIENT_SECRET: {{ .Values.carku.openid.clientSecret | quote }}
  {{- end }}
  {{- if ((.Values.carku).openid).clients }}
  OPENID_CLIENTS: {{ .Values.carku.openid.clients | quote }}
  {{- end }}
  {{- end }}

  {{- if ((.Values.carku).ldap) }}
  {{- if ((.Values.carku).ldap).user }}
  LDAP_USER: {{ .Values.carku.ldap.user | quote }}
  {{- end }}
  {{- if ((.Values.carku).ldap).password }}
  LDAP_PASSWORD: {{ .Values.carku.ldap.password | quote }}
  {{- end }}
  {{- end }}

  {{- if ((.Values.carku).geocoder).key }}
  GEOCODER_KEY: {{ .Values.carku.geocoder.key | quote }}
  {{- end }}

  {{- if ((.Values.carku).geolocation).key }}
  GEOLOCATION_KEY: {{ .Values.carku.geolocation.key | quote }}
  {{- end }}

  {{- if ((.Values.carku).mapMatcher).key }}
  MAP_MATCHER_KEY: {{ .Values.carku.mapMatcher.key | quote }}
  {{- end }}

  {{- if ((.Values.carku).forward).header }}
  FORWARD_HEADER: {{ .Values.carku.forward.header | quote }}
  {{- end }}

  {{- if ((.Values.carku).event).forward }}
  {{- if ((.Values.carku).event.forward).header }}
  EVENT_FORWARD_HEADER: {{ .Values.carku.event.forward.header | quote }}
  {{- end }}
  {{- end }}

  {{- if ((.Values.carku).mail).smtp }}
  {{- if ((.Values.carku).mail.smtp).username }}
  MAIL_SMTP_USERNAME: {{ .Values.carku.mail.smtp.username | quote }}
  {{- end }}
  {{- if ((.Values.carku).mail.smtp).password }}
  MAIL_SMTP_PASSWORD: {{ .Values.carku.mail.smtp.password | quote }}
  {{- end }}
  {{- end }}
{{- end }}